### ISSUE TITLE
Code Does Not Compile, Missing Difficulty Adjustment

### ISSUE THREAD

**Issue by HashEngineering** [dr0pthedoge/unitwallet-android#1]
There are many compiler errors when building this with gradle - It is clear that this source code is not what was used to publish the apk to Google Play.  With these and other errors, it is impossible to build this.

app/build.gradle:25:
`'-I' + file('src/main/secp/secp256k1'), '-I' + file('src/main/secp'), '-I' + file('src/main/jni/breadwallet-core'),`
This is what the line should be given that the folder under jni is `breadwallet`, not `unitwallet`.

Also the Difficulty Adjustment code is missing, it was removed from BRPeerManager.c

The is the original code from breadwallet-core/BRPeerManager.c:1205:
```
    // verify block difficulty
    if (r && ! BRMerkleBlockVerifyDifficulty(block, prev, transitionTime)) {
        peer_log(peer, "relayed block with invalid difficulty target %x, blockHash: %s", block->target,
                 u256_hex_encode(block->blockHash));
        r = 0;
    }

```

This is a very important piece of code, given the November 13 hard fork for the difficulty adjustment.

**Comment by HashEngineering** [comment]
Also in breadwallet-core/BRBIP32Sequence.h

`#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"`

This include would only work on the developers machine and certainly wouldn't work on a linux system given that the path is a Windows path.

**Comment by dr0pthedoge** [comment]
While I understand that you're having trouble compiling, but saying "I can't compile it, therefore it's not the real source code" is a false and baseless claim...

You said there were many compiler errors, so what are your compile errors, as in all of them?

**Comment by maemon** [comment]
Hey Hash, thanks for submitting the issue, as my dev said, could you please list all of the "compile errors" so that we can correct it. Thanks.

**Comment by HashEngineering** [comment]
Gradle Output is as follows:

```
Download https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.9.3/gradle-experimental-0.9.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/0.9.3/gradle-experimental-0.9.3.jar
please apply google-services plugin at the bottom of the build file.
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis-google-19-1' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-googl
e_apis-google-19')
Already observed package id 'add-ons;addon-google_apis-google-19' in 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis-google-19'. Skipping duplicate at 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_a
pis-google-19-1'
Observed package id 'add-ons;addon-google_apis_x86-google-19' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis_x86-google-19-1' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\add
on-google_apis_x86-google-19')
Observed package id 'build-tools;18.0.1' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\build-tools\android-4.3' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\build-tools\18.0.1')
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis-google-19-1' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-googl
e_apis-google-19')
Already observed package id 'add-ons;addon-google_apis-google-19' in 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis-google-19'. Skipping duplicate at 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_a
pis-google-19-1'
Observed package id 'add-ons;addon-google_apis_x86-google-19' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\addon-google_apis_x86-google-19-1' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\add-ons\add
on-google_apis_x86-google-19')
Observed package id 'build-tools;18.0.1' in inconsistent location 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\build-tools\android-4.3' (Expected 'D:\Development\adt-bundle-windows-x86_64-20130729\sdk\build-tools\18.0.1')
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDemoaDebugBuild UP-TO-DATE
:app:checkDemoaDebugManifest
:app:preDemoaReleaseBuild UP-TO-DATE
:app:preUnitDebugBuild UP-TO-DATE
:app:preUnitReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:app:prepareComAndroidSupportAppcompatV72531Library
:app:prepareComAndroidSupportCardviewV72531Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:app:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportGridlayoutV72531Library
:app:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComAndroidSupportSupportV132531Library
:app:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComAndroidSupportTransition2531Library
:app:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:app:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:app:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:app:prepareComGoogleAndroidGmsPlayServicesVision1104Library
:app:prepareComGoogleAndroidGmsPlayServicesVisionCommon1104Library
:app:prepareComGoogleFirebaseFirebaseAnalytics1104Library
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl1104Library
:app:prepareComGoogleFirebaseFirebaseCommon1104Library
:app:prepareComGoogleFirebaseFirebaseCore1104Library
:app:prepareComGoogleFirebaseFirebaseCrash1021Library
:app:prepareComGoogleFirebaseFirebaseIid1104Library
:app:prepareDemoaDebugDependencies
:app:compileCoreArm64-v8aDebugDemoaSharedLibraryCoreArm64-v8aDebugDemoaSharedLibraryMainC
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\BRBIP32Sequence.c:25:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file no
t found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^
1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\BRWallet.c:25:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRWallet.h:29:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRAddress.h:28:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\BRWallet.c:25:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRWallet.h:30:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file no
t found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^
1 warning and 1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\core.c:27:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition/wallet.h:25:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^
1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\BRPeerManager.c:25:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRPeerManager.h:28:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRPeer.h:30:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRAddress.h:28:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\BRPeerManager.c:25:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRPeerManager.h:31:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRWallet.h:30:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file no
t found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^
1 warning and 1 error generated.

D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\JNIBase58.c:7:10: fatal error: 'BRBase58.h' file not found
#include <BRBase58.h>
         ^
1 error generated.

D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\JNIKey.c:6:10: fatal error: 'BRInt.h' file not found
#include <BRInt.h>
         ^
1 error generated.

D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\JNIBIP32Sequence.c:6:10: fatal error: 'BRKey.h' file not found
#include <BRKey.h>
         ^
1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\PeerManager.c:25:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition/PeerManager.h:26:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^
1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\test.c:25:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core\test.c:28:
In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRWallet.h:30:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file no
t found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^
1 warning and 1 error generated.

In file included from D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition\wallet.c:25:
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\transition/wallet.h:25:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^
1 error generated.

:app:compileCoreArm64-v8aDebugDemoaSharedLibraryCoreArm64-v8aDebugDemoaSharedLibraryMainC FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugDemoaSharedLibraryCoreArm64-v8aDebugDemoaSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling BRBIP32Sequence.c.
      C compiler failed while compiling BRWallet.c.
      C compiler failed while compiling core.c.
      C compiler failed while compiling BRPeerManager.c.
      C compiler failed while compiling JNIBase58.c.
      C compiler failed while compiling JNIKey.c.
      C compiler failed while compiling JNIBIP32Sequence.c.
      C compiler failed while compiling PeerManager.c.
      C compiler failed while compiling test.c.
      C compiler failed while compiling wallet.c.
  See the complete log at: file:///D:/Documents/GitHub/unitwallet-android/app/build/tmp/compileCoreArm64-v8aDebugDemoaSharedLibraryCoreArm64-v8aDebugDemoaSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

These errors are fixed by two changes:

**The first change:**
```
D:\Documents\GitHub\unitwallet-android\app\src\main\jni\breadwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file no
t found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
```

The include should be `#include <stdard.h>` rather than `#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"`

This particular include could allow the app to be built by a developer's machine, but it will not work on any other.

**The second change is in app/build.gradle:48**
`'-I' + file('src/main/secp/secp256k1'), '-I' + file('src/main/secp'), '-I' + file('src/main/jni/unitwallet-core'),`

This line should be changed to:
`'-I' + file('src/main/secp/secp256k1'), '-I' + file('src/main/secp'), '-I' + file('src/main/jni/breadwallet-core'),`

or `src/main/jni/breadwallet-core` should be renamed to `unitwallet-core`

This particular error indicates that the developer's source code differs from that which is on GitHub as of commit e7424578e6bd40171d0bf313f8b40eab5c858e86.

**Comment by maemon** [comment]
Thanks Hash, we'll take this into account when we update the sourcecode with our upcoming 1.5.0 release.

**Comment by seoulbit** [comment]
> Thanks Hash, we'll take this into account when we update the sourcecode with our upcoming _1.5.0 release_.

What is the status on this? You are currently publishing **version 1.5.1**, and no one (except the Play Store publisher) has any idea what the source code is. I can confirm that what you have published here on github can not cleanly compile.

Under Thai law, are you allowed to say one thing on your website (say you are fully transparent and open source) and do another (refuse after repeated requests to publish your source as you promised)? I think if you did this America, you would have to consult an attorney before publishing on the Play Store.

**Comment by HashEngineering** [comment]
The website with this url (https://www.unitwallet.co/) mentions
> Our wallet is completely non custodial, meaning that only you are in control of your money, it is impossible for us to freeze, steal or track you spending, you don't have to trust us, just have a look at our code :)

I am not sure if it matters what laws a country may have, but the presentation that is made matters to the users who pay attention and care about open source software.  Open Source means that any of us could take the source code, build it and install it on our devices.  By having out of date, non-compile-able code it makes it difficult for others to audit, install or make pull requests that fix bugs or add features.

I would suggest that the developer first unwind the most recent commits which make it difficult to determine what code was changed (perhaps due to different line endings) and then commit the changes anew with clear, but short descriptions to indicate what changed.

Some of us are also very interested in seeing the difficulty adjustment code.  It is a critical part of keeping this app following the correct chain.  With the Bitcoin Cash Wallet app (that I do), I actually had a user who had his app following the bitcoin blockchain.  While this was fixed by adding a checkpoint past the fork, following Bitcoin would be impossible under the November 13 DAA (if that was done correctly).

**Comment by HashEngineering** [comment]
After seeing some commits being made in December, I decided to compile this app once again.

The when compiling, the first errors are from the same issue that I pointed out on November 1st (above). 

```
Error:In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:29:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.h:28:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeer.h:30:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.h:31:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRKey.c:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRKey.c:52:10: fatal error: 'secp256k1/src/basic-config.h' file not found
#include "secp256k1/src/basic-config.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/test.c:25:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/test.c:28:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.c:25:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/core.c:27:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.h:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:29:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/core.c:27:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.h:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/PeerManager.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/PeerManager.h:27:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.h:28:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeer.h:30:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/PeerManager.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/PeerManager.h:27:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRPeerManager.h:31:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.h:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:29:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.c:25:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/wallet.h:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRWallet.h:30:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/transition/JNIBIP32Sequence.c:7:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRBIP32Sequence.h:30:10: fatal error: '../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h' file not found
#include "../../../../../../../../AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/5.0.300080/include/stdarg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugUnitSharedLibraryCoreArm64-v8aDebugUnitSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling BRWallet.c.
      C compiler failed while compiling BRPeerManager.c.
      C compiler failed while compiling BRKey.c.
      C compiler failed while compiling test.c.
      C compiler failed while compiling BRBIP32Sequence.c.
      C compiler failed while compiling core.c.
      C compiler failed while compiling PeerManager.c.
      C compiler failed while compiling wallet.c.
      C compiler failed while compiling JNIBIP32Sequence.c.
  See the complete log at: file:///development/hashengineering/unitwallet-android/app/build/tmp/compileCoreArm64-v8aDebugUnitSharedLibraryCoreArm64-v8aDebugUnitSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```
If we fix that error my replacing one line with `#include <stdarg.h>`, then try again, we get this error.

```
Error:In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRKey.c:26:
In file included from /development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRAddress.h:28:
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
/development/hashengineering/unitwallet-android/app/src/main/jni/unitwallet-core/BRKey.c:52:10: fatal error: 'secp256k1/src/basic-config.h' file not found
#include "secp256k1/src/basic-config.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugUnitSharedLibraryCoreArm64-v8aDebugUnitSharedLibraryMainC'.
> A build operation failed.
      C compiler failed while compiling BRKey.c.
  See the complete log at: file:///development/hashengineering/unitwallet-android/app/build/tmp/compileCoreArm64-v8aDebugUnitSharedLibraryCoreArm64-v8aDebugUnitSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

This is from the missing submodule `secp256k1` 

Why is the submodule missing?

This commit deleted them:  https://github.com/dr0pthedoge/unitwallet-android/commit/3194a22e70c0e9bbb013acc8226551eac6688899

For the developer who has this on his machine, these errors that I pointed out wouldn't occur.  The submodules were present earlier, so the secp256k1 files would not be missing after deleting the contents of .gitmodules.  However, for the rest of us that would want to build this for our own device or fork it to submit pull requests with new features or bug fixes, we would need to do a lot of work to undo these errors.

**Comment by maemon** [comment]
Hey Hash, is there any way to pm you?

**Comment by HashEngineering** [comment]
My email is hashengineeringsolutions@gmail.com.  We can determine a pm method from there.

**Comment by zquestz** [comment]
I also had some issues with compilation. This might help, worked for me. https://github.com/zquestz/unitwallet-android/commit/316bdee5de57525118d310249349f7081f33ac9e

**Comment by HashEngineering** [comment]
@zquestz Those are definitely fixes that will address the issues I had.

Did you happen to find or write the November 13 DDA and the previous DDA?

**Comment by zquestz** [comment]
Actually I think that is committed, the redesign branch has commits from Dec.

**Comment by zquestz** [comment]
@HashEngineering any chance you looked to see if the DAA code was there in the latest pushes? I am curious and want to audit that part of the code base as well.

**Comment by maemon** [comment]
I've merged @zquestz pull request, see if you can compile it now @HashEngineering

**Comment by maemon** [comment]
@dr0pthedoge was in charged of writing the DAA for the app, I don't think he has merged the code on to this repo :(

**Comment by zquestz** [comment]
Well for some reason it connects to my ABC 0.16.2 node without any errors. Seemed it would freak out if the new DAA code wasn't there. If there is any way to get in touch with @dr0pthedoge and get the latest code posted then I would be happy to add more contributions. Really love the wallet.

**Comment by Stouse49** [comment]
@maemon:  I have taken the recent updates from @zquestz and found that this project does compile on my system.

> Regarding the DAA:  the first post in this issue noted the following:
> Also the Difficulty Adjustment code is missing, it was removed from BRPeerManager.c
> 
> The is the original code from breadwallet-core/BRPeerManager.c:1205:
> 
>     // verify block difficulty
>     if (r && ! BRMerkleBlockVerifyDifficulty(block, prev, transitionTime)) {
>         peer_log(peer, "relayed block with invalid difficulty target %x, blockHash: %s", block->target,
>                  u256_hex_encode(block->blockHash));
>         r = 0;
>     }

BRPeerManager.c:1194 is still missing this code.  Therefore, no difficulty checks are made and it might follow the correct Bitcoin Cash chain if it doesn't get side tracked on any forks (August 1 or November 13).  Following the correct chain is based on connecting to the right nodes.

The difficulty check method in BRMerkleBlock.c (BRMerkleBlockVerifyDifficulty) is missing the EDA DAA and the November 13 EDA.

Additionally, the checkpoints at the top of BRPeerManager.c do not include any of the hard fork blocks.  The blocks present are pre August 1 (before 478559).

**Comment by HashEngineering** [comment]
For the difficulty adjustment algorithms, the math functions contained in this liked file can be useful.
https://github.com/QuantumExplorer/dashwallet/blob/master/DashWallet/BRMerkleBlock.m#L241

The above code has functions written in C that handle big integer math necessary for calculating difficulty targets.
